server:
  port: 7090
spring:
  datasource:
    url: jdbc:h2:file:./.h2/todo
    driver-class-name: org.h2.Driver
    username: cc
    password: cc
    tomcat:
      default-auto-commit: true
  jpa:
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    properties:
      smtp:
        auth: true
        timeout: 25000
    username: cjj957225907@163.com
    password: qq0123456
  jackson:
    time-zone: GMT+8
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
logging:
  file: debug.log
ribbon:
  eureka:
    enabled: false
late:
  mail:
    sendto: chijingjia@tfrunning.com.cn
  workday:
    url: http://tool.bitefu.net/jiari/?d=$date