server:
  port: 7090
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/todo
  jpa:
    show-sql: true
  profiles:
    active: local
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    properties:
      smtp:
        auth: true
        timeout: 25000
    username: cjj957225907@163.com
    password: qq0123456
  jackson:
    time-zone: GMT+8
late:
  mail:
    sendto: chijingjia@tfrunning.com.cn